# Generated by Django 4.2.1 on 2023-06-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_profile',
            field=models.ImageField(null=True, upload_to='profile_photos'),
        ),
    ]
