# Generated by Django 4.2.1 on 2023-06-16 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='deleted',
            new_name='is_deleted',
        ),
    ]
