# Generated by Django 4.2.1 on 2023-06-16 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_app_backend', '0002_rename_deleted_message_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send_at',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='send_at_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
