# Generated by Django 4.2.1 on 2023-06-17 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_app_backend', '0003_message_send_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='send_at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_at_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
